### ISSUE TITLE
Upgrade from Tiki25 -> Tiki26 will require PHP 8.1 instead of PHP 7.4

### ISSUE THREAD

**Issue by marclaporte** [YunoHost-Apps/tiki_ynh#13]
Tiki has a new major version each 8 months. Every 3rd version is a Long Term Support (LTS), which is supported for 5 years. So there is some overlap between versions. All the details are here: https://tiki.org/Versions

As of 2023-06-09, YunoHost supports Tiki 24.x LTS and 25.x. Great!

Supporting Tiki 24.x LTS will be smooth as it will be just minor updates until March 2027:
https://doc.tiki.org/Tiki24

However, Tiki 25.x will reach end of life once Tiki 26.1 is released. So this means that the 25x -> 26x upgrade process should happen in 2023-07 or 2023-08. This upgrade will be a little special because requirements go from PHP 7.4 to PHP 8.1
https://doc.tiki.org/PHP8

@rodriguezny will propose a merge request for this, at the appropriate time.

**Comment by marclaporte** [comment]
https://github.com/YunoHost-Apps/tiki_ynh/pull/22

**Comment by ericgaspar** [comment]
closing with #24
