### ISSUE TITLE
Determine version policy for Tiki Wiki CMS Groupware on YunoHost

### ISSUE THREAD

**Issue by marclaporte** [YunoHost-Apps/tiki_ynh#4]
Tiki has a new major version each 8 months. Every 3rd version is a Long Term Support (LTS), which is supported for 5 years. So there is some overlap between versions. All the details are here: https://tiki.org/Versions

For now, I recommend that YunoHost sticks to LTS versions, and thus, upgrade to 24.2 LTS (and not soon-to-be-released 25.0)

**Comment by ericgaspar** [comment]
Closing with #5
